# 1. Extract Data

#### Extract data dari file projects_data.csv kemudian sesuaikan tipe data, cek missing values, duplikasi data, dan lain-lain.

In [33]:
import pandas as pd

In [50]:
file_path = "C:/Users/ASUS/mini_project_alta_zahra/dataset/projects_data.csv"
projects = pd.read_csv(file_path)
print(projects)

            id                   regionname  \
0      P162228                        Other
1      P163962                       Africa
2      P167672                   South Asia
3      P158768                   South Asia
4      P161364                       Africa
...        ...                          ...
18243  P006578  Latin America and Caribbean
18244  P037451      Europe and Central Asia
18245  P037362      Europe and Central Asia
18246  P037452      Europe and Central Asia
18247  P037383      Europe and Central Asia

                                             countryname prodline  \
0                                            World;World       RE
1      Democratic Republic of the Congo;Democratic Re...       PE
2      People's Republic of Bangladesh;People's Repub...       PE
3      Islamic  Republic of Afghanistan;Islamic  Repu...       PE
4      Federal Republic of Nigeria;Federal Republic o...       PE
...                                                  ...      ...
18243                Republic of Chile;Republic of Chile       PE
18244  Grand Duchy of Luxembourg;Grand Duchy of Luxem...       PE
18245              Kingdom of Denmark;Kingdom of Denmark       PE
18246  Kingdom of the Netherlands;Kingdom of the Neth...       PE
18247                    French Republic;French Republic       PE

                       lendinginstr lendinginstrtype envassesmentcategorycode  \
0      Investment Project Financing               IN                        C
1      Investment Project Financing               IN                        B
2      Investment Project Financing               IN                      NaN
3      Investment Project Financing               IN                        A
4      Investment Project Financing               IN                        B
...                             ...              ...                      ...
18243      Specific Investment Loan               IN                      NaN
18244    Structural Adjustment Loan               AD                      NaN
18245    Structural Adjustment Loan               AD                      NaN
18246    Structural Adjustment Loan               AD                      NaN
18247    Structural Adjustment Loan               AD                      NaN

      supplementprojectflg productlinetype projectstatusdisplay  ...  \
0                        N               L               Active  ...
1                        N               L               Active  ...
2                        Y               L               Active  ...
3                        N               L               Active  ...
4                        N               L               Active  ...
...                    ...             ...                  ...  ...
18243                    N               L               Closed  ...
18244                    N               L               Closed  ...
18245                    N               L               Closed  ...
18246                    N               L               Closed  ...
18247                    N               L               Closed  ...

      mjtheme3name mjtheme4name mjtheme5name  \
0              NaN          NaN          NaN
1              NaN          NaN          NaN
2              NaN          NaN          NaN
3              NaN          NaN          NaN
4              NaN          NaN          NaN
...            ...          ...          ...
18243          NaN          NaN          NaN
18244          NaN          NaN          NaN
18245          NaN          NaN          NaN
18246          NaN          NaN          NaN
18247          NaN          NaN          NaN

                                                location  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4      0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...
...                                                  ...
18243                                                NaN
18244                                                NaN
18245                                                NaN
18246                                                NaN
18247                                                NaN

                                                GeoLocID  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4      0002327546;0002328925;0002565340;0002565343;00...
...                                                  ...
18243                                                NaN
18244                                                NaN
18245                                                NaN
18246                                                NaN
18247                                                NaN

                                              GeoLocName  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4      Ogun State;Niger State;Abia State;Edo;Kebbi St...
...                                                  ...
18243                                                NaN
18244                                                NaN
18245                                                NaN
18246                                                NaN
18247                                                NaN

                      Latitude               Longitude            Country  \
0                          NaN                     NaN                NaN
1                          NaN                     NaN                NaN
2                          NaN                     NaN                NaN
3                          NaN                     NaN                NaN
4      7;10;5.41667;6.5;11.5;8  3.58333;6;7.5;6;4;10.5  NG;NG;NG;NG;NG;NG
...                        ...                     ...                ...
18243                      NaN                     NaN                NaN
18244                      NaN                     NaN                NaN
18245                      NaN                     NaN                NaN
18246                      NaN                     NaN                NaN
18247                      NaN                     NaN                NaN

      Unnamed: 56
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
18243         NaN
18244         NaN
18245         NaN
18246         NaN
18247         NaN

[18248 rows x 57 columns]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_19740\3949144204.py:2: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  projects = pd.read_csv(file_path)

#### Mengecek missing values

In [51]:
missing_values = projects.isnull().sum()
missing_values

id                              0
regionname                      0
countryname                     0
prodline                        0
lendinginstr                  246
lendinginstrtype              246
envassesmentcategorycode     5811
supplementprojectflg           53
productlinetype                 0
projectstatusdisplay            4
status                          4
project_name                    0
boardapprovaldate            1504
board_approval_month         1504
closingdate                  3349
lendprojectcost               125
ibrdcommamt                     0
idacommamt                      0
totalamt                        0
grantamt                        0
borrower                     5919
impagency                    6097
url                             0
projectdoc                  18248
majorsector_percent         18248
sector1                         0
sector2                      8721
sector3                     11761
sector4                     13872
sector5                     15535
sector                        638
mjsector1                   18248
mjsector2                   18248
mjsector3                   18248
mjsector4                   18248
mjsector5                   18248
mjsector                      638
theme1                          0
theme2                       8395
theme3                      10764
theme4                      13014
theme5                      15320
theme                       18248
goal                         6115
financier                   11188
mjtheme1name                18248
mjtheme2name                18248
mjtheme3name                18248
mjtheme4name                18248
mjtheme5name                18248
location                    13922
GeoLocID                    13922
GeoLocName                  13923
Latitude                    13922
Longitude                   13922
Country                     14045
Unnamed: 56                 18248
dtype: int64

#### Mengecek duplikasi data

In [52]:
duplicate_rows = projects[projects.duplicated()]
duplicate_rows

Empty DataFrame
Columns: [id, regionname, countryname, prodline, lendinginstr, lendinginstrtype, envassesmentcategorycode, supplementprojectflg, productlinetype, projectstatusdisplay, status, project_name, boardapprovaldate, board_approval_month, closingdate, lendprojectcost, ibrdcommamt, idacommamt, totalamt, grantamt, borrower, impagency, url, projectdoc , majorsector_percent , sector1, sector2, sector3, sector4, sector5, sector, mjsector1, mjsector2, mjsector3, mjsector4, mjsector5, mjsector, theme1, theme2, theme3, theme4, theme5, theme , goal, financier, mjtheme1name, mjtheme2name, mjtheme3name, mjtheme4name, mjtheme5name, location, GeoLocID, GeoLocName, Latitude, Longitude, Country, Unnamed: 56]
Index: []

[0 rows x 57 columns]

# 2. Transform

#### Penyesuaian tipe data untuk dataset projects_data.csv

In [53]:
# from pandas import to_datetime

# data_types = {'id': str, 'regionname': str, 'countryname': str, 'prodline': str, 'boardapprovaldate':to_datetime, 'closingdate':to_datetime}  
# projects = pd.read_csv(file_path, dtype=data_types, low_memory=False)
# print(projects)

In [54]:
columns_to_drop = ['sector1', 'sector2', 'sector3', 'sector4', 'sector5',
                   'mjsector1', 'mjsector2', 'mjsector3', 'mjsector4', 'mjsector5', 'mjsector',
                   'theme1', 'theme2', 'theme3', 'theme4', 'theme5', 'goal', 'financier',
                   'mjtheme1name', 'mjtheme2name', 'mjtheme3name', 'mjtheme4name', 'mjtheme5name',
                   'location', 'GeoLocID', 'GeoLocName', 'Latitude', 'Longitude', 'Country', 'Unnamed: 56']

# Menghapus kolom-kolom yang tidak diperlukan
projects = projects.drop(columns=columns_to_drop)

print(projects)

            id                   regionname  \
0      P162228                        Other
1      P163962                       Africa
2      P167672                   South Asia
3      P158768                   South Asia
4      P161364                       Africa
...        ...                          ...
18243  P006578  Latin America and Caribbean
18244  P037451      Europe and Central Asia
18245  P037362      Europe and Central Asia
18246  P037452      Europe and Central Asia
18247  P037383      Europe and Central Asia

                                             countryname prodline  \
0                                            World;World       RE
1      Democratic Republic of the Congo;Democratic Re...       PE
2      People's Republic of Bangladesh;People's Repub...       PE
3      Islamic  Republic of Afghanistan;Islamic  Repu...       PE
4      Federal Republic of Nigeria;Federal Republic o...       PE
...                                                  ...      ...
18243                Republic of Chile;Republic of Chile       PE
18244  Grand Duchy of Luxembourg;Grand Duchy of Luxem...       PE
18245              Kingdom of Denmark;Kingdom of Denmark       PE
18246  Kingdom of the Netherlands;Kingdom of the Neth...       PE
18247                    French Republic;French Republic       PE

                       lendinginstr lendinginstrtype envassesmentcategorycode  \
0      Investment Project Financing               IN                        C
1      Investment Project Financing               IN                        B
2      Investment Project Financing               IN                      NaN
3      Investment Project Financing               IN                        A
4      Investment Project Financing               IN                        B
...                             ...              ...                      ...
18243      Specific Investment Loan               IN                      NaN
18244    Structural Adjustment Loan               AD                      NaN
18245    Structural Adjustment Loan               AD                      NaN
18246    Structural Adjustment Loan               AD                      NaN
18247    Structural Adjustment Loan               AD                      NaN

      supplementprojectflg productlinetype projectstatusdisplay  ...  \
0                        N               L               Active  ...
1                        N               L               Active  ...
2                        Y               L               Active  ...
3                        N               L               Active  ...
4                        N               L               Active  ...
...                    ...             ...                  ...  ...
18243                    N               L               Closed  ...
18244                    N               L               Closed  ...
18245                    N               L               Closed  ...
18246                    N               L               Closed  ...
18247                    N               L               Closed  ...

        idacommamt     totalamt grantamt borrower impagency  \
0                0            0  500,000      NaN       NaN
1      200,000,000  200,000,000        0      NaN       NaN
2       58,330,000   58,330,000        0      NaN       NaN
3       20,000,000   20,000,000        0     IIST      IIST
4      100,000,000  100,000,000        0      NaN       NaN
...            ...          ...      ...      ...       ...
18243            0   13,500,000        0      NaN       NaN
18244            0   12,000,000        0      NaN       NaN
18245            0   40,000,000        0      NaN       NaN
18246            0  195,000,000        0      NaN       NaN
18247            0  250,000,000        0      NaN       NaN

                                                     url projectdoc   \
0          http://projects.worldbank.org/P162228?lang=en         NaN
1          http://projects.worldbank.org/P163962?lang=en         NaN
2          http://projects.worldbank.org/P167672?lang=en         NaN
3          http://projects.worldbank.org/P158768?lang=en         NaN
4          http://projects.worldbank.org/P161364?lang=en         NaN
...                                                  ...         ...
18243  http://projects.worldbank.org/P006578/power-ir...         NaN
18244  http://projects.worldbank.org/P037451/steel-mi...         NaN
18245  http://projects.worldbank.org/P037362/post-war...         NaN
18246  http://projects.worldbank.org/P037452/post-war...         NaN
18247  http://projects.worldbank.org/P037383/reconstr...         NaN

      majorsector_percent                                              sector  \
0                      NaN                                                NaN
1                      NaN                                                NaN
2                      NaN                                                NaN
3                      NaN                                                NaN
4                      NaN  Social Protection;Social Protection;Other Indu...
...                    ...                                                ...
18243                  NaN                    (Historic)Hydro;(Historic)Hydro
18244                  NaN  (Historic)Economic management;(Historic)Econom...
18245                  NaN  (Historic)Economic management;(Historic)Econom...
18246                  NaN  (Historic)Economic management;(Historic)Econom...
18247                  NaN  (Historic)Economic management;(Historic)Econom...

      theme
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
...      ...
18243    NaN
18244    NaN
18245    NaN
18246    NaN
18247    NaN

[18248 rows x 27 columns]

#### Mengisi nilai yang hilang menggunakan string kosong(")

In [56]:
projects_filled_strings = projects.fillna('')

# Menyimpan dataframe yang sudah diisi nilai
file_path_filled_strings = "../dataset/projects_data_filled_strings.csv"
projects_filled_strings.to_csv(file_path_filled_strings, index=False)

In [57]:
# Menampilkan informasi tentang dataframe yang sudah diisi nilai
print("Informasi Dataframe Setelah Diisi dengan String Kosong:")
print(projects_filled_strings.info())

Informasi Dataframe Setelah Diisi dengan String Kosong:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18248 entries, 0 to 18247
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        18248 non-null  object
 1   regionname                18248 non-null  object
 2   countryname               18248 non-null  object
 3   prodline                  18248 non-null  object
 4   lendinginstr              18248 non-null  object
 5   lendinginstrtype          18248 non-null  object
 6   envassesmentcategorycode  18248 non-null  object
 7   supplementprojectflg      18248 non-null  object
 8   productlinetype           18248 non-null  object
 9   projectstatusdisplay      18248 non-null  object
 10  status                    18248 non-null  object
 11  project_name              18248 non-null  object
 12  boardapprovaldate         18248 non-null  object
 13  board_approval_month      18248 non-null  object
 14  closingdate               18248 non-null  object
 15  lendprojectcost           18248 non-null  object
 16  ibrdcommamt               18248 non-null  object
 17  idacommamt                18248 non-null  object
 18  totalamt                  18248 non-null  object
 19  grantamt                  18248 non-null  object
 20  borrower                  18248 non-null  object
 21  impagency                 18248 non-null  object
 22  url                       18248 non-null  object
 23  projectdoc                18248 non-null  object
 24  majorsector_percent       18248 non-null  object
 25  sector                    18248 non-null  object
 26  theme                     18248 non-null  object
dtypes: object(27)
memory usage: 3.8+ MB
None

#### Dummy Variables untuk dataset projects_data.csv